apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: default
spec:
  encryptedData:
    token: AgAqLP7R0F1gkBTPIsbDJ2+HP63AWegr38/Gpry6Lbq64jyPWVb05ivDUU+hKSMyTL3pUe9TrBbtbTOKBW6GcPNgjPSDBphNE0E10zqtMWpV974FayOM5q8NQGtUoAOpGzmxTe9wuDj0GtBohZUTN7eiOQhYfsxLyaEv1JkK/fn6RTOtc7xZYI8iX+yoQ/ipJsEEFTCEEUEungXk0CAcIJKLSC9JQPIkKzAENez+EsSYFpaFRoQQhzwajft+vvrQ7ajT8CXIFwplcu/DuqO6tnYcB7TQsMFHlEqk7FlxMJSXqx1fMW4+shUn2IAqLPsSVOIfyMKMY9mdJl90MY2nXpd29dqH0Q0ch/YR4vYdvpTUfTnnU7b2qygwXfe4lV3lmmqbOGtm/vuumyeaYJRD88M1nsXhFn4XQiZLRwy1N9I5jZ7mim8HhLCCLlHc9oxVgF/dOLqXb/P3iNKmomTYuJSJqQAk3PCGiBmBPTRl8HcVT/LPuSOdIg6Cci2bctm8joQsMYnOTbtY4er0q+gQNCnfbJr5opfpkuKX5SElWhc3w5EoC1RtcyTzoPB+DOFMFwXPNftKBwCwN8cw1Ycgx6EfKkBDSPtJsUL1gGZFD0naIjUYRHDD/58AgJM+Olq2znE8VuMFrO2hVJS2I/Z3w9YX7T3p3dv6XDldp5gQRp7huDXEqGxBk/dYRhMpgf/ocuRcqcl/QoAdjjzT66QnCiuQwGmzos7Zp7z3N2HBDu3Fx3SnLyY=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: default
    type: Opaque

